<!-- FORM AJOUT ARTICLE -->


<form action="/admin/article/add" method="POST" >
    <fieldset>
        <legend>Ajouter un article</legend>
        <div class="mb-3">
            <label for="title_article">Titre de l'article</label>
            <input class="form-control" type="text" name="title_article" id="title_article" value="<?=htmlspecialchars($title_article);?>">
            <?php if (isset($errors['title_article'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['title_article']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3">
            <label for="title_category">Quelle catégorie pour cet article ?</label>
                <select name="category" id="category-select">
                    <option value="">--Choisissez une catégorie--</option>
                    <option value="<?=htmlspecialchars($title_category);?>"></option>
                </select>

            <input class="form-control" type="text" name="title_category" id="title_category" value="<?=htmlspecialchars($title_category);?>">
            <?php if (isset($errors['title_category'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['title_category']);?></p>
            <?php endif; ?>
        </div>

        <div class="mb-3">
            <label for="description">Description de l'article</label>
            <input class="form-control" type="text" name="description" id="description" value="<?=htmlspecialchars($description);?>">
            <?php if (isset($errors['description'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3">
            <label for="prix">Prix de l'article</label>
            <input class="form-control" type="int" name="prix" id="prix" value="<?=htmlspecialchars($prix);?>">
            <?php if (isset($errors['prix'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['prix']);?></p>
            <?php endif; ?>
        </div>
        
        <input class="btn btn-primary" type="submit" value="Valider">
    </fieldset>
</form>