<!-- FORM AJOUT ARTICLE -->

<div class="text-center pt-3 pb-2">
    <h2 class="my-4">Ajouter une catégorie et/ou un article</h2>
</div>

<form action="/add_article" method="POST" >
    <fieldset>
        <legend>Ajouter un article</legend>
        <div class="mb-3">
            <label for="title_article">Titre de l'article</label>
            <input class="form-control" type="text" name="title_article" id="title_article" value="<?=htmlspecialchars($title_article);?>">
            <?php if (isset($errors['title_article'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['title_article']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3">
            <label for="description">Description de l'article</label>
            <input class="form-control" type="text" name="description" id="description" value="<?=htmlspecialchars($description);?>">
            <?php if (isset($errors['description'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3">
            <label for="prix">Prix de l'article</label>
            <input class="form-control" type="int" name="prix" id="prix" value="<?=htmlspecialchars($prix);?>">
            <?php if (isset($errors['prix'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['prix']);?></p>
            <?php endif; ?>
        </div>
        
        <input class="btn btn-primary" type="submit" value="Valider">
    </fieldset>
</form>