<!-- FORM AJOUT PRODUIT -->

<div class="text-center pt-3 pb-2">
    <h2 class="my-4">Ajouter un produit</h2>
</div>

<form action="/admin/product/add" method="POST" >
    <fieldset>
        <div class="p-4">
            <label for="title_product">Titre du produit</label>
            <input class="form-control" type="text" name="title_product" id="title_product" value="<?=htmlspecialchars($title_product);?>">
            <?php if (isset($errors['title_product'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['title_product']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="accessories">Accessoires liés au produit</label>
            <textarea class="form-control" type="text-area" name="accessories" id="accessories" rows="4" cols="50" value="<?=htmlspecialchars($accessories);?>"></textarea>
            <?php if (isset($errors['accessories'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['accessories']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="title_category">Quelle catégorie pour ce produit ?</label>
                <select name="category" id="category-select">
                    <option value="">--Choisissez une catégorie--</option>
                    <option value="<?=htmlspecialchars($title_category);?>"></option>
                </select>
        </div>
        <div class="p-4">
            <label for="technic">Technique utilisée</label>
                <select name="technic" id="technic">
                    <option value="">--Choisissez une technique--</option>
                    <option value="<?=htmlspecialchars($title_technic);?>"></option>
                </select>
        </div>
        <div class="p-4">
            <label for="price">Prix du produit</label>
            <input class="form-control" type="number" name="price" id="price" value="<?=htmlspecialchars($price);?>">
            <?php if (isset($errors['price'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['price']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="description">Description du produit</label>
            <textarea class="form-control" type="text-area" name="description" id="description" rows="8" cols="50" value="<?=htmlspecialchars($description);?>"></textarea>
            <?php if (isset($errors['description'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="the_most">Les + du produit</label>
            <textarea class="form-control" type="text-area" name="the_most" id="the_most" rows="8" cols="50" value="<?=htmlspecialchars($the_most);?>"></textarea>
            <?php if (isset($errors['the_most'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['the_most']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="features">La composition du produit</label>
            <textarea class="form-control" type="text-area" name="features" id="features" rows="8" cols="50" value="<?=htmlspecialchars($features);?>"></textarea>
            <?php if (isset($errors['features'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['features']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="dimensions">Les dimensions du produit</label>
            <textarea class="form-control" type="text-area" name="dimensions" id="dimensions" rows="8" cols="50" value="<?=htmlspecialchars($dimensions);?>"></textarea>
            <?php if (isset($errors['dimensions'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['dimensions']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-4">
            <label for="precision_description">Précisions sur le produit</label>
            <textarea class="form-control" type="text-area" name="precision_description" id="precision_description" rows="5" cols="50" value="<?=htmlspecialchars($precision_description);?>"></textarea>
            <?php if (isset($errors['precision_description'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['precision_description']);?></p>
            <?php endif; ?>
        </div>

        <div class="p-2">
        <input class="btn btn-primary" type="submit" value="Valider l'ajout du produit">
        </div>
    </fieldset>

</form>