<!-- ADMIN
    Liens vers les pages de création de catégories et de produits -->
<br>
<a href="<?=buildUrl('admin_add_category')?>">Ajouter une catégorie</a> <br>
<a href="<?=buildUrl('admin_add_technic')?>">Ajouter une technique</a> <br>
<a href="<?=buildUrl('admin_add_product')?>">Ajouter un produit</a> <br> <br>

<a href="<?=buildUrl('admin_list_category')?>">Liste des catégories</a> <br>
<a href="<?=buildUrl('admin_list_technic')?>">Liste des techniques</a> <br>
<a href="<?=buildUrl('admin_list_product')?>">Liste des produits</a> <br>

