<!-- ADMIN
    Liens vers les pages de création de catégories et de produits -->

<a href="<?=buildUrl('admin_add_category')?>">Ajouter une catégorie</a>
<a href="<?=buildUrl('admin_add_product')?>">Ajouter un produit</a>
<a href="<?=buildUrl('admin_add_technic')?>">Ajouter une technique</a>
<a href="<?=buildUrl('admin_list_category')?>">Liste des catégories existantes</a>
<a href="<?=buildUrl('admin_list_technic')?>">Liste des techniques existantes</a>
<a href="<?=buildUrl('admin_list_product')?>">Liste des produits</a>   
