<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Admin</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="https://kit.fontawesome.com/8475ba8bc0.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Overlock+SC&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Overlock+SC&family=Overlock:wght@400;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= asset('css/style.css') ?>">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</head>

<body>
    <!-- Header -->
    <header>
        <img src="<?= asset('img/logo.png') ?>" alt="Logo Maison A.C." class="logo-admin">
        <h1 class="dashboardTitre">DASHBOARD ADMINISTRATEUR</h1>
        <!-- <a class="dashboardTitre" href="<?= buildUrl('admin') ?>">
                <font style="vertical-align: inherit;">
                    <font style="vertical-align: inherit;">DASHBOARD ADMINISTRATEUR</font>
                </font>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Basculer la navigation">
            </button> -->
        <a class="sitePublic" href="<?= buildUrl('home') ?>">
            <font style="vertical-align: inherit;">
                <font style="vertical-align: inherit;">RETOUR AU SITE PUBLIC</font>
            </font>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Basculer la navigation">
        </button>

        <!-- NavBar -->
        <!-- MODE CONNECTE -->

        <!-- DASHBOARD ADMIN -->
        <!-- Barre de navigation du Dashboard ADMIN -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">

            </div>
            <br>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle show" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">
                                    Catégories
                                </font>
                            </font>
                        </a>
                        <ul class="dropdown-menu" data-bs-popper="static">
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_list_category') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Liste</font>
                                    </font>
                                </a></li>
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_add_category') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Ajouter</font>
                                    </font>
                                </a></li>
                        </ul>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle show" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">
                                    Techniques
                                </font>
                            </font>
                        </a>
                        <ul class="dropdown-menu" data-bs-popper="static">
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_list_technic') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Liste</font>
                                    </font>
                                </a></li>
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_add_technic') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Ajouter</font>
                                    </font>
                                </a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle show" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">
                                    Produits
                                </font>
                            </font>
                        </a>
                        <ul class="dropdown-menu" data-bs-popper="static">
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_list_product') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Liste</font>
                                    </font>
                                </a></li>
                            <li><a class="dropdown-item" href="<?= buildUrl('admin_add_product') ?>">
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">Ajouter</font>
                                    </font>
                                </a></li>
                        </ul>
                    </li>
                </ul>
                <?php if (isConnected()) : ?>
                    <a class="navdisconnect" href="<?= buildUrl('logout'); ?>">
                        Déconnexion
                    </a>
                <?php endif; ?>
            </div>





        </nav>
    </header>

    <!-- Main -->
    <main class="main">

        <!-- Affichage du message flash le cas échéant -->
        <?php if (isset($flashMessage)) : ?>
            <div class="alert alert-success text-center pt-3 pb-4"><?= htmlspecialchars($flashMessage); ?></div>
        <?php endif; ?>


        <!-- inclusion du template spécifique à la page affichée -->
        <?php include '../templates/' . $template . '.phtml'; ?>

    </main>
</body>

<!-- Footer -->
<footer class="footer">
</footer>

</html>