<!-- FORM MODIFICATION CATEGORIE -->


<div class="text-center pt-3 pb-2">
    <h2 class="my-4">Modifier une catégorie</h2>
</div>

<form action="<?=buildUrl('admin_edit_category', ['id_category' => $categoryId])?>" method="POST" >
    <fieldset>
        <div class="mt-4 p-5">
            <label for="title_category">Titre de la catégorie</label>
            <input class="form-control" type="text" name="title_category" id="title_category" value="<?=htmlspecialchars($title);?>">
            <?php if (isset($errors['title_category'])): ?>
                <p class="alert alert-danger"><?=htmlspecialchars($errors['title_category']);?></p>
            <?php endif; ?>
        </div>
        <div class="p-2 text-center">
            <input class="btn btn-primary" type="submit" value="Valider la modification de la catégorie">
        </div>
    </fieldset>
    
</form>