<!-- Liste des produits -->


<div class="text-center pt-3 pb-2">
    <h2 class="my-4">Liste des produits</h2>

<table class="table table-striped bg-white">
<thead>
<tr>
  <th scope="col">#id</th>
  <th scope="col">Titre</th>
  <th scope="col">Image</th>
  <th scope="col">Accessoires</th>
  <th scope="col">Prix</th>
  <th scope="col">Description</th>
  <th scope="col">Les +</th>
  <th scope="col">Caractéristiques</th>
  <th scope="col">Dimensions</th>
  <th scope="col">Précisions</th>
  <th scope="col">N° Catégorie</th>
  <th scope="col">N° Technique</th>

</tr>
</thead>
<tbody>
<?php 
    foreach ($products as $product): ?>
        <tr class="fw-normal">
            <td class="align-middle">
                <span><?=htmlspecialchars($product['id_product']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['title_product']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['image']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['accessories']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['price']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['description']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['the_most']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['features']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['dimensions']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['precision_description']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['id_category']);?></span>
            </td>
            <td class="align-middle">
                <span><?=htmlspecialchars($product['id_technic']);?></span>
            </td>
            <td class="align-middle">
                <a href=<?="/admin/product/edit?id_product={$product['id_product']}"?> data-mdb-toggle="tooltip" title="Modifier">
                    <i class="fa-solid fa-pen-to-square fa-lg text-secondary me-auto"></i>
                </a> <hr>
                <a href=<?="/admin/product/delete?id_product={$product['id_product']}"?> data-mdb-toggle="tooltip" title="Supprimer">
                    <i class="fas fa-trash-alt fa-lg text-danger"></i>
                </a>
            </td>
    <?php endforeach; ?>
</tbody>
</table>

</div>

