 <!-- Main Page Catalog -->
 <main class="catalog-main">
     <?php foreach ($categories as $category) { ?>
         <div>
             <a href="<?= buildUrl('category', ['id_category' => intval($category['id_category'])]) ?>">
                 <img class="catalog-card" src="<?= asset('img/category/' . $category['image']) ?>" alt="Image de la catégorie Roses" width="220px" height="300px">
                 <h3 class="catalog-titre"><?= htmlspecialchars($category['title_category']) ?></h3>
             </a>
         </div>
     <?php
        } ?>
 </main>