 <!-- Main page category -->

<main>
    <!-- Récupération du titre de la catégorie choisie -->
    <h1>
        <?php
        ?>
    </h1>

    <!-- Affichage du 1er article de la catégorie -->
    <!-- Récupération du titre de l'article, de son prix -->
    <!-- Photos (slide) et bouton aperçu rapide -->
    <section class="article01">
        <?php
        ?>
    </section>

</main>

<!-- Affichage du message flash le cas échéant -->
<?php if ($flashMessage): ?>
    <div class="alert alert-success text-center pt-3 pb-4"><?=htmlspecialchars($flashMessage);?></div>
<?php endif; ?>