 <!-- Main page contact -->

 <main>
    <!-- Récupération du titre de la page contact -->
    <h1>
        <?php
        ?>
    </h1>

    <!-- Affichage du formulaire de contatc -->
    <!-- icônes Appelez-nous, Ecrivez-nous, Atelier situé en Provence -->

</main>

<!-- Affichage du message flash le cas échéant -->
<?php if ($flashMessage): ?>
    <div class="alert alert-success text-center pt-3 pb-4"><?=htmlspecialchars($flashMessage);?></div>
<?php endif; ?>