    <!-- Main -->
    <main class="main">
        <div class="container">
            <img src="img/imgAccueil.jpg" alt="Image d'accueil" class="imgAccueil">
            <div class="text">
                <p class="p-1">Angélique Chevalier vous propose une collection d'articles élégants et originaux confectionnés avec amour dans son atelier en Provence.</p>
                <p class="p-2">Pièces uniques, idées cadeaux, accessoires ou encore envie de chiffons et de jolies choses ?</p>
                <p class="p-3">Venez explorer l’univers créatif de la Maison A.C. Vous y trouverez harmonie d’élégance et de simplicité, authenticité et délicatesse mais aussi enchantement féérique et un brin de mignonnerie !</p>
                <p class="p-4">Bon voyage !</p>
            </div>
        </div>
    </main>                         

<!-- Affichage du message flash le cas échéant -->
<?php if ($flashMessage): ?>
    <div class="alert alert-success text-center pt-3 pb-4"><?=htmlspecialchars($flashMessage);?></div>
<?php endif; ?>

