    <!-- Main -->
    <main class="main-home">
        <h1 class="homeTitle">Bienvenu dans la boutique de la Maison A.C. !</h1>
        <div class="container-home">
            <img class="imgAccueil" src="img/imgAccueil.jpg" alt="Image d'accueil">
            <div class="text-home">
                <p class="p-1">Angélique Chevalier vous propose une collection d'articles élégants et originaux confectionnés avec amour dans son atelier en Provence.</p>
                <p class="p-2">Pièces uniques, idées cadeaux, accessoires ou encore envie de chiffons et de jolies choses ?</p>
                <p class="p-3">Venez explorer l'univers créatif de la Maison A.C. Vous y trouverez harmonie d'élégance et de simplicité, authenticité et délicatesse mais aussi enchantement féérique et un brin de mignonnerie !</p>
                <p class="p-4">Bon voyage !</p>
            </div>
        </div>
    </main>