    <!-- Main -->
    <main class="main-home">
        <h1 class="homeTitle">Bienvenu dans la boutique de la Maison A.C. !</h1>
        <div class="container-home">
            <img class="imgAccueil" srcset="img/imgAccueil.jpg 1900w, img/imgAccueilMobile.jpg 360w" sizes="(max-width: 576px) 360px, (max-width: 768px) 540px, 700px" alt="Image d'accueil">
            <div class="text-home">
                <p class="p-1">Angélique Chevalier vous propose une collection d'articles élégants et originaux confectionnés avec amour dans son atelier en Provence.</p>
                <p class="p-2">Pièces uniques, idées cadeaux, accessoires ou encore envie de chiffons et de jolies choses ?</p>
                <p class="p-3">Venez explorer l'univers créatif de la Maison A.C. Vous y trouverez harmonie d'élégance et de simplicité, authenticité et délicatesse mais aussi enchantement féérique et un brin de mignonnerie !</p>
                <p class="p-4">Bon voyage !</p>

                <div class="slider">
                    <div class="slider-layout">
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/01-roses75cacf9d83ec4c02ec3a64aa49bda2112bb0ecf3.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les roses</figcaption>
                        </figure>
                        <figure class="slider-figure active">
                            <img class="slider-picture" src="img/category/02-lingettes-panierdc35c782a592a70b8b88bfc2792458463848847a.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les paniers et lingettes</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/00-lingettes-supp7a26ae8f9c3a19050b2108b52e5af15f3455542e.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Lingettes</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/00-cotons-rondsfe955199632d70f2eb5a8b1cce2f257ef02ab033.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Cotons ronds</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/03-acc-cuisine2a53e69169160f67cef5582be70c3d3fed518a50.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les acccessoires de cuisine</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/04-panier-linge85370f6b527968ba51f1fbc596f3923dcfdbb625.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les paniers à linge</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/05-tour-cou3f3506db0e510272330d3bba652ddf9e17c294e6.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les tours de cou</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/06-boites2435160354597e14bf72b33b922760661c84e89d.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les boîtes</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/07-etui-mouchoirs342688a7a72c05b3dad78867e39e821793144362.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les étuis à mouchoirs</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/08-porte-monnaieb68c7dce8f2a002142eba3198107db2570117fcb.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les portes-monnaie</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/09-sacc11a66cec867cb715d7a86e73b344c5bb1770137.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les sacs</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/10-support-cartesc5358306b26ee1ca6409008eceae730430b64d4c.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Le support de cartes</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/11-vide-poches42839ed9a899f10c0d3f2ab13fa88420c163f82f.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les vide-poches</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/12-trousses31f74b27051ca2bdfcd61e53c3893fb282082d9e.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les trousses</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/13-porte-jeton58f1c469609d9424f36c1ba1e69a5a1478eeecca.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les porte-jetons</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/14-berlingots0f0dda749dd2871d769b744ec96572863db1105b.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les berlingots -lavande ou romarins-</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/15-portefeuille6aaee60302d278fa5c2290841a3fd5c2afe6aa80.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les portefeuilles</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/16-jeux-eveil211f04ab3c1b73518e04291c2905a9e959ef9f94.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les jeux d'éveil</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/17-amigurumisea291f5f22030dee5a26dba5d82c41e634aca79c.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les amigurumis</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/18-poupees0631c1d4b13b9e4856e478d90dd6ebec8fc3a9a2.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les poupées</figcaption>
                        </figure>
                        <figure class="slider-figure">
                            <img class="slider-picture" src="img/category/19-frivolites7335c8e62fbc8ce44c68c56fed87af84c7b136bd.jpg" alt="Image d'un produit">
                            <figcaption class="slider-legend">Les frivolités</figcaption>
                        </figure>

                        <nav class="slider-navigation">
                            <a href="#" rel="prev" id="prev" class="prev" title="Image précédente">
                                <i class="fas fa-chevron-left" aria-hidden="true"></i>
                            </a>
                            <a href="#" rel="next" id="next" class="next" title="Image suivante">
                                <i class="fas fa-chevron-right" aria-hidden="true"></i>
                            </a>
                        </nav>
                    </div>

                </div>
            </div>
        </div>


    </main>


    <script src="<?= asset('js/slider.js') ?>"></script>
    <script src="<?= asset('js/slider-product.js') ?>"></script>