 <!-- Main page product -->

 <main>

     <!-- Récupération du titre du produit choisi -->
     <h1>
         <?php
            $title = $product->getTitle();
            ?>
     </h1>

     <!-- Affichage du produit -->

     <!-- Affichage de la photo du produit (slide) + petites photos en-dessous -->
     <section class="section-1G">
         <div id='carouselExampleIndicators' class='carousel slide' data-ride='carousel'>
             <img src="img/01_panier_gris_pailleté/01_ensemble.jpg" alt="Photo du panier gris pailleté et de ses lingettes et cotons">
             <img src="img/01_panier_gris_pailleté/02_vuedessus.jpg" alt="Photo du panier vu de dessus">
             <img src="img/01_panier_gris_pailleté/03a.jpg" alt="Photo du panier et de ses lingettes et cotons">
             <img src="img/01_panier_gris_pailleté/03b.jpg" alt="Photo du panier et de ses lingettes et cotons">
             <img src="img/01_panier_gris_pailleté/04.jpg" alt="Photo du panier et de ses lingettes et cotons">
             <img src="img/01_panier_gris_pailleté/05.jpg" alt="Photo du panier et de ses lingettes et cotons">
         </div>
         <button id="prevBtn">Précédent</button>
         <button id="nextBtn">Suivant</button>
     </section>

     <!-- Réupération du titre du produit, de son prix -->
     <section class="section-1D">
         <?php
            $title = htmlspecialchars(stripcslashes($_GET['title']));
            $accessory = htmlspecialchars(stripcslashes($_GET['accessory']));
            $price = number_format($product->getPrice(), 2); // On formatte le prix avec deux décimales.
            ?>

         <!-- Boutons quantité et ajouter au panier -->
         <?php
            $quantity = htmlspecialchars(stripcslashes($_GET['accessory']));
            ?>
         <input type="Ajouter au panier">
         <!-- Texte "Fabrication artisanales..." -->
         <div>
             <p>Fabrication artisanale réalisée par Angélique Chevalier au sein de l'atelier de la Maison A.C.</p>
         </div>
     </section>

     <!-- Icones Livraison, paiement et création unique -->
     <section class="section-2D">
         <div>
             <img src="img/livraison.jpg" alt="Icône de livraison rapide">
             <h4>Livraison rapide</h4>
         </div>
         <div>
             <img src="img/paiement.png" alt="Icône de paiement sécurisé">
             <h4>Paiement sécurisé</h4>
         </div>
         <div>
             <img src="img/coeur.png" alt="Icône de création unique">
             <h4>Création unique</h4>
         </div>
     </section>

     <!-- Affichage de la desription complète -->
     <section class="section-3Centre">
         <?php
            $description = htmlspecialchars(stripcslashes($_GET['description']));
            $plus = htmlspecialchars(stripcslashes($_GET['plus']));
            $composition = htmlspecialchars(stripcslashes($_GET['composition']));
            $dimensions = htmlspecialchars(stripcslashes($_GET['dimensions']));
            $precision_description = htmlspecialchars(stripcslashes($_GET['precision_description']));
            ?>
     </section>

     <script src="script-product.js"></script>

 </main>