 <!-- Main page pruduct -->

 <main>
    <!-- Récupération du titre du produit choisi -->
    <h1>
        <?php
        ?>
    </h1>

    <!-- Affichage du produit -->
    <!-- Affichage de la photo du produit (slide) + petites photos en-dessous -->
    <!-- Réupération du titre du produit, de son prix -->
    <!-- Boutons quantité et ajouter au panier -->
    <!-- Texte "Fabrication artisanales..." -->
    <!-- Icones Livraison, paiement et création unique -->
    <!-- Affichage de la desription complète -->



    <section class="article01">
        <?php
        ?>
    </section>

</main>